version: '3.8'

services:
  #define the service name
  api:
    container_name: career-sparker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - .:/career_sparker
#    depends_on:
#      - redis
    environment:
        - DJANGO_SETTINGS_MODULE=careersparker.settings
    env_file:
        - .env_dev  # Use the .env_dev file for development

#  # define the redis service
#  redis:
#    image: redis:latest
#    container_name: career-sparker-redis
#    ports:
#      - "6379:6379"
#
#
#  # define the Celery worker service
#  celery_worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: career-sparker-celery-worker
#    command: celery -A careersparker.celery worker --loglevel=info -c 10 -O fair -P prefork -n cel_app_worker
#    volumes:
#      - .:/career_sparker
#    depends_on:
#      - api
#      - redis
#    env_file:
#      - .env_dev  # Use the .env_dev file for development
